import "./globals.css";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";
import LayoutClient from "@/components/layout/layout-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      </head>

      <body className={inter.className}>
        <link rel="icon" href="favicon.ico" sizes="any" />
        <Suspense fallback={<Loading />}>
          <LayoutClient />
          <main className="bg-gradient-to-r bg-[#ede6f2] dark:bg-black box-border min-h-screen w-screen max-w-full overflow-hidden pt-20 pb-32 px-6 sm:px-10 sm:pb-48 lg:py-10 lg:pr-40 lg:pl-16">
            <div className="fixed top-0 left-0 w-full h-screen bg-[radial-gradient(circle_at_-70%,rgba(95,32,181,0.5)_0%,rgba(95,32,181,0.3)_1%,rgba(0,0,0,0)_80%)]"/>
            <div className="relative z-10">
              {children}
            </div>
          </main>
        </Suspense>
      </body>
    </html>
  );
}
