"use client";

import Header from "@/components/layout/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import { useEffect, useState } from "react";
import NavbarFloat from "@/components/layout/NavbarFloat";
import NavbarFloatRight from "@/components/layout/NavbarFloatRight";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [width, setWidth] = useState<number | null>(null);

  useEffect(() => {
    function windowResize() {
      setWidth(window.innerWidth);
    }

    if (
      localStorage.theme === "dark" ||
      (!("theme" in localStorage) &&
        window.matchMedia("(prefers-color-scheme: dark)").matches)
    ) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }

    window.addEventListener("resize", windowResize);
    setWidth(window.innerWidth);

    return () => {
      window.removeEventListener("resize", windowResize);
    };
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          {width ? width! < 768 ? <Header /> : null : null}
          <main className="bg-gradient-to-r  from-[#f4f1f7] to-[#d6cfd6]  dark:bg-gradient-to-r dark:from-[#393c52] dark:to-[#1a1b25] box-border min-h-screen w-screen max-w-full overflow-hidden py-20 px-6 sm:px-10 sm:pb-48 lg:py-10 lg:pr-40 lg:pl-16">
            {children}
          </main>
          {width ? width! < 768 ? <Navbar /> : null : null}
          {width ? (
            width! >= 768 && width! < 1024 ? (
              <NavbarFloat />
            ) : null
          ) : null}
          {width ? width! >= 1024 ? <NavbarFloatRight /> : null : null}
        </Suspense>
      </body>
    </html>
  );
}
